INSERT INTO words
  (english_word, meaning, example_sentence, translation, level, category, is_active, created_at, updated_at)
VALUES
('get along with', '', 'I get along with my coworkers really well.', 'Tôi có quan hệ rất tốt với đồng nghiệp.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('looking forward to', '', 'I''m looking forward to the weekend.', 'Tôi đang mong chờ cuối tuần.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('come up with', '', 'Can you come up with a better solution?', 'Bạn có thể nghĩ ra giải pháp tốt hơn không?', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('put off', '', 'Don''t put off until tomorrow what you can do today.', 'Đừng hoãn đến ngày mai những gì bạn có thể làm hôm nay.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('break the ice', '', 'He told a joke to break the ice at the meeting.', 'Anh ấy kể một câu chuyện cười để phá vỡ sự im lặng trong cuộc họp.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('piece of cake', '', 'The exam was a piece of cake.', 'Bài thi dễ như ăn bánh.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('call it a day', '', 'It''s getting late. Let''s call it a day.', 'Đã muộn rồi. Hãy kết thúc công việc hôm nay thôi.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('hit the nail on the head', '', 'You hit the nail on the head with that comment.', 'Bạn đã nói đúng với nhận xét đó.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('once in a blue moon', '', 'I only see him once in a blue moon.', 'Tôi chỉ thấy anh ấy rất hiếm khi.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('the ball is in your court', '', 'I''ve made my offer. The ball is in your court now.', 'Tôi đã đưa ra đề nghị. Bây giờ đến lượt bạn quyết định.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('take care of', '', 'I take care of my plants every day.', 'Tôi chăm sóc cây cối mỗi ngày.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('get rid of', '', 'I need to get rid of old clothes.', 'Tôi cần loại bỏ quần áo cũ.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('look after', '', 'Can you look after my dog?', 'Bạn có thể trông nom con chó của tôi không?', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('turn down', '', 'I had to turn down the job offer.', 'Tôi phải từ chối lời mời làm việc.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('find out', '', 'I need to find out what happened.', 'Tôi cần tìm ra điều gì đã xảy ra.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('give up', '', 'Don''t give up on your dreams.', 'Đừng từ bỏ ước mơ của bạn.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('go through', '', 'We''re going through a difficult time.', 'Chúng tôi đang trải qua thời kỳ khó khăn.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('look up', '', 'I''ll look up the word in the dictionary.', 'Tôi sẽ tra cứu từ này trong từ điển.', 'BEGINNER', 'ACADEMIC', true, NOW(), NOW()),,
('make up', '', 'Don''t make up excuses.', 'Đừng bịa đặt lý do.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('pick up', '', 'I''ll pick you up at 8 AM.', 'Tôi sẽ đón bạn lúc 8 giờ sáng.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('run out of', '', 'We''ve run out of milk.', 'Chúng tôi đã hết sữa.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('turn on', '', 'Please turn on the lights.', 'Làm ơn bật đèn lên.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('turn off', '', 'Don''t forget to turn off the TV.', 'Đừng quên tắt TV.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('look for', '', 'I''m looking for my keys.', 'Tôi đang tìm chìa khóa của tôi.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('take off', '', 'The plane will take off soon.', 'Máy bay sẽ cất cánh sớm.', 'BEGINNER', 'TRAVEL', true, NOW(), NOW()),,
('run into', '', 'I ran into an old friend.', 'Tôi gặp một người bạn cũ.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('set up', '', 'Let me set up the meeting.', 'Để tôi thiết lập cuộc họp.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('show up', '', 'He didn''t show up at the party.', 'Anh ấy không đến bữa tiệc.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('turn up', '', 'Can you turn up the volume?', 'Bạn có thể tăng âm lượng không?', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('work out', '', 'I work out three times a week.', 'Tôi tập thể dục ba lần một tuần.', 'BEGINNER', 'SPORTS', true, NOW(), NOW()),,
('figure out', '', 'I need to figure out the problem.', 'Tôi cần tìm ra vấn đề.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('point out', '', 'He pointed out my mistake.', 'Anh ấy chỉ ra lỗi của tôi.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('bring up', '', 'Don''t bring up that topic.', 'Đừng đề cập chủ đề đó.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('carry out', '', 'We need to carry out the plan.', 'Chúng tôi cần thực hiện kế hoạch.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('catch up', '', 'I need to catch up on my work.', 'Tôi cần bắt kịp công việc của tôi.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('check out', '', 'Let''s check out that new restaurant.', 'Hãy thử nhà hàng mới đó xem.', 'BEGINNER', 'FOOD', true, NOW(), NOW()),,
('fill in', '', 'Please fill in this form.', 'Làm ơn điền vào mẫu này.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('get back', '', 'I''ll get back to you tomorrow.', 'Tôi sẽ liên hệ lại với bạn ngày mai.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('give in', '', 'Don''t give in to pressure.', 'Đừng nhượng bộ trước áp lực.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('go ahead', '', 'Go ahead and start the meeting.', 'Tiếp tục và bắt đầu cuộc họp.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('hand in', '', 'Please hand in your homework.', 'Làm ơn nộp bài tập về nhà.', 'BEGINNER', 'ACADEMIC', true, NOW(), NOW()),,
('hold on', '', 'Hold on, I''ll be right back.', 'Đợi một chút, tôi sẽ quay lại ngay.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('keep up', '', 'Keep up the good work!', 'Tiếp tục phát huy!', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('let down', '', 'Don''t let me down.', 'Đừng làm tôi thất vọng.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('make out', '', 'I can''t make out what you''re saying.', 'Tôi không thể nghe rõ bạn đang nói gì.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('pass away', '', 'He passed away last year.', 'Ông ấy qua đời năm ngoái.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('put on', '', 'Put on your coat, it''s cold.', 'Mặc áo khoác vào, trời lạnh đấy.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('run away', '', 'The dog ran away from home.', 'Con chó chạy trốn khỏi nhà.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('set off', '', 'We set off early in the morning.', 'Chúng tôi khởi hành sớm vào buổi sáng.', 'BEGINNER', 'TRAVEL', true, NOW(), NOW()),,
('take over', '', 'She will take over the company.', 'Cô ấy sẽ tiếp quản công ty.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('think over', '', 'Let me think over your proposal.', 'Để tôi suy nghĩ về đề nghị của bạn.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('try on', '', 'I want to try on this dress.', 'Tôi muốn thử chiếc váy này.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('wake up', '', 'I wake up at 6 AM every day.', 'Tôi thức dậy lúc 6 giờ sáng mỗi ngày.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('work on', '', 'I''m working on a new project.', 'Tôi đang làm việc trên một dự án mới.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('break down', '', 'My car broke down on the highway.', 'Xe của tôi bị hỏng trên đường cao tốc.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('bring about', '', 'This policy will bring about change.', 'Chính sách này sẽ mang lại thay đổi.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('call for', '', 'This situation calls for immediate action.', 'Tình huống này đòi hỏi hành động ngay lập tức.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('carry on', '', 'Carry on with your work.', 'Tiếp tục công việc của bạn.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('come across', '', 'I came across an old photo.', 'Tôi tình cờ gặp một bức ảnh cũ.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('deal with', '', 'We need to deal with this problem.', 'Chúng ta cần giải quyết vấn đề này.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('end up', '', 'We ended up at the wrong place.', 'Chúng tôi cuối cùng đến nhầm chỗ.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('get away', '', 'I want to get away from the city.', 'Tôi muốn rời khỏi thành phố.', 'BEGINNER', 'TRAVEL', true, NOW(), NOW()),,
('get on', '', 'Get on the bus at the next stop.', 'Lên xe buýt ở trạm tiếp theo.', 'BEGINNER', 'TRAVEL', true, NOW(), NOW()),,
('get off', '', 'Get off the train at Central Station.', 'Xuống tàu ở ga Trung tâm.', 'BEGINNER', 'TRAVEL', true, NOW(), NOW()),,
('give away', '', 'I''ll give away my old books.', 'Tôi sẽ cho đi những cuốn sách cũ của mình.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('go on', '', 'Go on, tell me more.', 'Tiếp tục đi, kể cho tôi nghe thêm.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('hang out', '', 'Let''s hang out this weekend.', 'Hãy đi chơi cuối tuần này.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('hold back', '', 'Don''t hold back your emotions.', 'Đừng kìm nén cảm xúc của bạn.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('look into', '', 'I''ll look into this matter.', 'Tôi sẽ điều tra vấn đề này.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('make for', '', 'This will make for a better future.', 'Điều này sẽ tạo nên một tương lai tốt hơn.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('pass by', '', 'I pass by the park every day.', 'Tôi đi ngang qua công viên mỗi ngày.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('put away', '', 'Put away your toys.', 'Cất đồ chơi của bạn đi.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('run over', '', 'The car ran over a cat.', 'Chiếc xe đã cán qua một con mèo.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('set out', '', 'We set out on our journey.', 'Chúng tôi bắt đầu hành trình của mình.', 'BEGINNER', 'TRAVEL', true, NOW(), NOW()),,
('stand up', '', 'Please stand up when the teacher enters.', 'Làm ơn đứng dậy khi giáo viên vào.', 'BEGINNER', 'ACADEMIC', true, NOW(), NOW()),,
('take in', '', 'I couldn''t take in all the information.', 'Tôi không thể tiếp thu tất cả thông tin.', 'INTERMEDIATE', 'ACADEMIC', true, NOW(), NOW()),,
('throw away', '', 'Don''t throw away this opportunity.', 'Đừng vứt bỏ cơ hội này.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('turn around', '', 'Turn around and face me.', 'Quay lại và nhìn tôi.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('break up', '', 'They broke up last month.', 'Họ chia tay tháng trước.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('bring back', '', 'This brings back memories.', 'Điều này gợi lại những kỷ niệm.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('call off', '', 'They called off the meeting.', 'Họ đã hủy cuộc họp.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('come back', '', 'When will you come back?', 'Khi nào bạn sẽ quay lại?', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('cut down', '', 'I need to cut down on sugar.', 'Tôi cần giảm đường.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('drop off', '', 'I''ll drop off the package at your office.', 'Tôi sẽ giao gói hàng tại văn phòng của bạn.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('fall apart', '', 'Everything seems to fall apart.', 'Mọi thứ dường như sụp đổ.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('get by', '', 'I can get by with less money.', 'Tôi có thể sống với ít tiền hơn.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('go off', '', 'The alarm went off at 6 AM.', 'Chuông báo thức kêu lúc 6 giờ sáng.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('hand out', '', 'The teacher handed out the papers.', 'Giáo viên phát giấy.', 'BEGINNER', 'ACADEMIC', true, NOW(), NOW()),,
('keep on', '', 'Keep on trying!', 'Tiếp tục cố gắng!', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('let in', '', 'Please let me in.', 'Làm ơn cho tôi vào.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('look forward to', '', 'I''m looking forward to seeing you.', 'Tôi mong được gặp bạn.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('make up for', '', 'I''ll make up for lost time.', 'Tôi sẽ bù đắp thời gian đã mất.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('pass on', '', 'Please pass on the message.', 'Làm ơn chuyển lời nhắn.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('pull off', '', 'We managed to pull off the event.', 'Chúng tôi đã thành công tổ chức sự kiện.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('put up with', '', 'I can''t put up with this noise.', 'Tôi không thể chịu đựng tiếng ồn này.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('run across', '', 'I ran across an interesting article.', 'Tôi tình cờ đọc một bài báo thú vị.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('see off', '', 'I''ll see you off at the airport.', 'Tôi sẽ tiễn bạn ở sân bay.', 'BEGINNER', 'TRAVEL', true, NOW(), NOW()),,
('show off', '', 'Don''t show off your wealth.', 'Đừng khoe khoang của cải.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('sit down', '', 'Please sit down.', 'Làm ơn ngồi xuống.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('take after', '', 'She takes after her mother.', 'Cô ấy giống mẹ.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('think about', '', 'I need to think about this decision.', 'Tôi cần suy nghĩ về quyết định này.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('wait for', '', 'I''ll wait for you here.', 'Tôi sẽ đợi bạn ở đây.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('break in', '', 'Someone tried to break in last night.', 'Ai đó đã cố gắng đột nhập đêm qua.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('bring forward', '', 'Let''s bring forward the meeting.', 'Hãy đưa cuộc họp lên sớm hơn.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('call up', '', 'I''ll call you up later.', 'Tôi sẽ gọi cho bạn sau.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('come in', '', 'Come in, please.', 'Xin mời vào.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('cut out', '', 'Cut out the unnecessary parts.', 'Cắt bỏ những phần không cần thiết.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('do away with', '', 'We should do away with this rule.', 'Chúng ta nên bãi bỏ quy tắc này.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('fall for', '', 'I fell for her immediately.', 'Tôi đã yêu cô ấy ngay lập tức.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('get around', '', 'How do you get around the city?', 'Bạn đi lại trong thành phố như thế nào?', 'INTERMEDIATE', 'TRAVEL', true, NOW(), NOW()),,
('go along with', '', 'I''ll go along with your plan.', 'Tôi sẽ đồng ý với kế hoạch của bạn.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('hand over', '', 'Please hand over the documents.', 'Làm ơn giao tài liệu.', 'BEGINNER', 'BUSINESS', true, NOW(), NOW()),,
('keep away', '', 'Keep away from the fire.', 'Tránh xa lửa.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('let out', '', 'Don''t let out the secret.', 'Đừng tiết lộ bí mật.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('look down on', '', 'Don''t look down on others.', 'Đừng coi thường người khác.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('put forward', '', 'I put forward a new proposal.', 'Tôi đưa ra một đề nghị mới.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('run out', '', 'Time is running out.', 'Thời gian sắp hết.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('set aside', '', 'Set aside some money for emergencies.', 'Để dành một ít tiền cho trường hợp khẩn cấp.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('stand by', '', 'I''ll stand by you.', 'Tôi sẽ ủng hộ bạn.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('take on', '', 'I''ll take on this challenge.', 'Tôi sẽ đảm nhận thử thách này.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('throw out', '', 'Throw out the garbage.', 'Vứt rác đi.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('turn in', '', 'Please turn in your assignments.', 'Làm ơn nộp bài tập.', 'BEGINNER', 'ACADEMIC', true, NOW(), NOW()),,
('watch out', '', 'Watch out for cars!', 'Cẩn thận xe!', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('break out', '', 'A fire broke out last night.', 'Một đám cháy đã bùng phát đêm qua.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('bring round', '', 'I''ll bring round some drinks.', 'Tôi sẽ mang theo một ít đồ uống.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('catch on', '', 'This trend is catching on quickly.', 'Xu hướng này đang lan truyền nhanh chóng.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('come along', '', 'Come along with us!', 'Đi cùng chúng tôi!', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('cut back', '', 'We need to cut back on expenses.', 'Chúng ta cần cắt giảm chi phí.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('do up', '', 'Do up your buttons.', 'Cài nút của bạn.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('fall back on', '', 'I can always fall back on my savings.', 'Tôi luôn có thể dựa vào khoản tiết kiệm.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('get ahead', '', 'Work hard to get ahead.', 'Làm việc chăm chỉ để tiến bộ.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('go back', '', 'I want to go back home.', 'Tôi muốn về nhà.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('hang on', '', 'Hang on, I''m coming!', 'Đợi một chút, tôi đang đến!', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('hold on to', '', 'Hold on to your dreams.', 'Giữ lấy ước mơ của bạn.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('look out', '', 'Look out! There''s a car coming.', 'Coi chừng! Có xe đang đến.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('make off with', '', 'The thief made off with the money.', 'Kẻ trộm đã cuỗm tiền đi.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('put down', '', 'Put down your phone.', 'Đặt điện thoại xuống.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('see through', '', 'I can see through your lies.', 'Tôi có thể nhìn thấu lời nói dối của bạn.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('show around', '', 'Let me show you around the city.', 'Để tôi dẫn bạn đi tham quan thành phố.', 'BEGINNER', 'TRAVEL', true, NOW(), NOW()),,
('sit up', '', 'Sit up straight!', 'Ngồi thẳng lên!', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('take apart', '', 'I need to take apart this machine.', 'Tôi cần tháo rời chiếc máy này.', 'INTERMEDIATE', 'TECHNOLOGY', true, NOW(), NOW()),,
('think up', '', 'Let''s think up a solution.', 'Hãy nghĩ ra một giải pháp.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('turn out', '', 'It turned out to be true.', 'Hóa ra là đúng.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('wait on', '', 'The waiter will wait on you.', 'Người phục vụ sẽ phục vụ bạn.', 'INTERMEDIATE', 'FOOD', true, NOW(), NOW()),,
('wear out', '', 'These shoes are worn out.', 'Đôi giày này đã mòn.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('break through', '', 'We need to break through the barrier.', 'Chúng ta cần vượt qua rào cản.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('catch up with', '', 'I need to catch up with my studies.', 'Tôi cần bắt kịp việc học.', 'INTERMEDIATE', 'ACADEMIC', true, NOW(), NOW()),,
('come down', '', 'The prices came down significantly.', 'Giá cả đã giảm đáng kể.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('cut off', '', 'The phone was cut off.', 'Điện thoại bị cắt.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('do without', '', 'I can do without coffee.', 'Tôi có thể sống mà không cần cà phê.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('fall through', '', 'The plan fell through.', 'Kế hoạch đã thất bại.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('get at', '', 'What are you getting at?', 'Bạn đang muốn nói gì?', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('go through with', '', 'I''ll go through with the plan.', 'Tôi sẽ thực hiện kế hoạch.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('keep to', '', 'Keep to the schedule.', 'Tuân thủ lịch trình.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('let up', '', 'The rain finally let up.', 'Cuối cùng mưa cũng tạnh.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('look up to', '', 'I look up to my teacher.', 'Tôi ngưỡng mộ giáo viên của tôi.', 'INTERMEDIATE', 'ACADEMIC', true, NOW(), NOW()),,
('pass over', '', 'I was passed over for promotion.', 'Tôi đã bị bỏ qua không được thăng chức.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('put through', '', 'I''ll put you through to the manager.', 'Tôi sẽ chuyển máy cho người quản lý.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('see to', '', 'I''ll see to this matter.', 'Tôi sẽ xử lý vấn đề này.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('shut down', '', 'The factory shut down last year.', 'Nhà máy đã đóng cửa năm ngoái.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('stand for', '', 'What does this stand for?', 'Cái này có nghĩa là gì?', 'INTERMEDIATE', 'ACADEMIC', true, NOW(), NOW()),,
('take back', '', 'I want to take back what I said.', 'Tôi muốn rút lại những gì tôi đã nói.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('think through', '', 'Think through the consequences.', 'Suy nghĩ kỹ về hậu quả.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('turn into', '', 'The caterpillar turned into a butterfly.', 'Con sâu đã biến thành con bướm.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('wait up', '', 'Wait up! I''m coming.', 'Đợi với! Tôi đang đến.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('wind up', '', 'We wound up in Paris.', 'Chúng tôi cuối cùng đến Paris.', 'INTERMEDIATE', 'TRAVEL', true, NOW(), NOW()),,
('break out of', '', 'They broke out of prison.', 'Họ đã vượt ngục.', 'ADVANCED', 'DAILY_LIFE', true, NOW(), NOW()),,
('catch on to', '', 'I finally caught on to the joke.', 'Cuối cùng tôi cũng hiểu được câu chuyện cười.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('come up against', '', 'We came up against many obstacles.', 'Chúng tôi đã gặp nhiều trở ngại.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('cut in', '', 'Don''t cut in line!', 'Đừng chen hàng!', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('do over', '', 'I need to do over this project.', 'Tôi cần làm lại dự án này.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('fall behind', '', 'Don''t fall behind on your payments.', 'Đừng chậm trễ trong việc thanh toán.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('get away with', '', 'You can''t get away with this.', 'Bạn không thể thoát tội với việc này.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('go back on', '', 'Don''t go back on your word.', 'Đừng nuốt lời.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('hang up', '', 'Don''t hang up on me!', 'Đừng cúp máy!', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('hold out', '', 'Hold out your hand.', 'Đưa tay ra.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('make up to', '', 'I''ll make it up to you.', 'Tôi sẽ bù đắp cho bạn.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('pass up', '', 'Don''t pass up this opportunity.', 'Đừng bỏ lỡ cơ hội này.', 'INTERMEDIATE', 'BUSINESS', true, NOW(), NOW()),,
('put up', '', 'Can you put me up for the night?', 'Bạn có thể cho tôi ở nhờ một đêm không?', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('run down', '', 'I feel run down.', 'Tôi cảm thấy kiệt sức.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('see about', '', 'I''ll see about getting tickets.', 'Tôi sẽ lo việc lấy vé.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('shut up', '', 'Shut up and listen!', 'Im lặng và lắng nghe!', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('stand out', '', 'You really stand out in the crowd.', 'Bạn thực sự nổi bật trong đám đông.', 'INTERMEDIATE', 'DAILY_LIFE', true, NOW(), NOW()),,
('think of', '', 'What do you think of this idea?', 'Bạn nghĩ gì về ý tưởng này?', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),,
('turn on to', '', 'I''m really turned on to jazz music.', 'Tôi thực sự thích nhạc jazz.', 'INTERMEDIATE', 'ENTERTAINMENT', true, NOW(), NOW()),,
('watch over', '', 'Please watch over the children.', 'Làm ơn trông nom bọn trẻ.', 'BEGINNER', 'DAILY_LIFE', true, NOW(), NOW()),;