-- Update meaning field with Vietnamese translations
UPDATE words SET meaning = 'Có quan hệ tốt với ai đó' WHERE english_word = 'get along with';
UPDATE words SET meaning = 'Mong chờ, háo hức về điều gì đó' WHERE english_word = 'looking forward to';
UPDATE words SET meaning = 'Nghĩ ra, đưa ra ý tưởng' WHERE english_word = 'come up with';
UPDATE words SET meaning = 'Hoãn lại, trì hoãn' WHERE english_word = 'put off';
UPDATE words SET meaning = 'Phá vỡ sự im lặng, bắt đầu cuộc trò chuyện' WHERE english_word = 'break the ice';
UPDATE words SET meaning = 'Rất dễ dàng' WHERE english_word = 'piece of cake';
UPDATE words SET meaning = 'Kết thúc công việc trong ngày' WHERE english_word = 'call it a day';
UPDATE words SET meaning = 'Nói đúng, chính xác' WHERE english_word = 'hit the nail on the head';
UPDATE words SET meaning = 'Rất hiếm khi' WHERE english_word = 'once in a blue moon';
UPDATE words SET meaning = 'Đến lượt bạn quyết định' WHERE english_word = 'the ball is in your court';
UPDATE words SET meaning = 'Chăm sóc, quan tâm' WHERE english_word = 'take care of';
UPDATE words SET meaning = 'Loại bỏ, vứt bỏ' WHERE english_word = 'get rid of';
UPDATE words SET meaning = 'Trông nom, chăm sóc' WHERE english_word = 'look after';
UPDATE words SET meaning = 'Từ chối' WHERE english_word = 'turn down';
UPDATE words SET meaning = 'Tìm ra, phát hiện' WHERE english_word = 'find out';
UPDATE words SET meaning = 'Từ bỏ, đầu hàng' WHERE english_word = 'give up';
UPDATE words SET meaning = 'Trải qua, vượt qua' WHERE english_word = 'go through';
UPDATE words SET meaning = 'Tra cứu, tìm kiếm' WHERE english_word = 'look up';
UPDATE words SET meaning = 'Bịa đặt, tạo ra' WHERE english_word = 'make up';
UPDATE words SET meaning = 'Đón, nhặt lên' WHERE english_word = 'pick up';
UPDATE words SET meaning = 'Hết, cạn kiệt' WHERE english_word = 'run out of';
UPDATE words SET meaning = 'Bật lên' WHERE english_word = 'turn on';
UPDATE words SET meaning = 'Tắt đi' WHERE english_word = 'turn off';
UPDATE words SET meaning = 'Tìm kiếm' WHERE english_word = 'look for';
UPDATE words SET meaning = 'Cất cánh, cởi ra' WHERE english_word = 'take off';
UPDATE words SET meaning = 'Tình cờ gặp' WHERE english_word = 'run into';
UPDATE words SET meaning = 'Thiết lập, sắp xếp' WHERE english_word = 'set up';
UPDATE words SET meaning = 'Xuất hiện, đến' WHERE english_word = 'show up';
UPDATE words SET meaning = 'Tăng lên, xuất hiện' WHERE english_word = 'turn up';
UPDATE words SET meaning = 'Tập thể dục, giải quyết' WHERE english_word = 'work out';
UPDATE words SET meaning = 'Tìm ra, hiểu ra' WHERE english_word = 'figure out';
UPDATE words SET meaning = 'Chỉ ra, nhấn mạnh' WHERE english_word = 'point out';
UPDATE words SET meaning = 'Đề cập, nuôi dưỡng' WHERE english_word = 'bring up';
UPDATE words SET meaning = 'Thực hiện, tiến hành' WHERE english_word = 'carry out';
UPDATE words SET meaning = 'Bắt kịp, đuổi kịp' WHERE english_word = 'catch up';
UPDATE words SET meaning = 'Kiểm tra, xem xét' WHERE english_word = 'check out';
UPDATE words SET meaning = 'Điền vào' WHERE english_word = 'fill in';
UPDATE words SET meaning = 'Quay lại, liên hệ lại' WHERE english_word = 'get back';
UPDATE words SET meaning = 'Nhượng bộ, đầu hàng' WHERE english_word = 'give in';
UPDATE words SET meaning = 'Tiếp tục, bắt đầu' WHERE english_word = 'go ahead';
UPDATE words SET meaning = 'Nộp, giao nộp' WHERE english_word = 'hand in';
UPDATE words SET meaning = 'Đợi, giữ' WHERE english_word = 'hold on';
UPDATE words SET meaning = 'Tiếp tục, duy trì' WHERE english_word = 'keep up';
UPDATE words SET meaning = 'Làm thất vọng' WHERE english_word = 'let down';
UPDATE words SET meaning = 'Nghe rõ, hiểu được' WHERE english_word = 'make out';
UPDATE words SET meaning = 'Qua đời' WHERE english_word = 'pass away';
UPDATE words SET meaning = 'Mặc vào, đặt lên' WHERE english_word = 'put on';
UPDATE words SET meaning = 'Chạy trốn' WHERE english_word = 'run away';
UPDATE words SET meaning = 'Khởi hành, bắt đầu' WHERE english_word = 'set off';
UPDATE words SET meaning = 'Tiếp quản, đảm nhận' WHERE english_word = 'take over';
UPDATE words SET meaning = 'Suy nghĩ kỹ' WHERE english_word = 'think over';
UPDATE words SET meaning = 'Thử, mặc thử' WHERE english_word = 'try on';
UPDATE words SET meaning = 'Thức dậy' WHERE english_word = 'wake up';
UPDATE words SET meaning = 'Làm việc trên, thực hiện' WHERE english_word = 'work on';
UPDATE words SET meaning = 'Bị hỏng, suy sụp' WHERE english_word = 'break down';
UPDATE words SET meaning = 'Mang lại, gây ra' WHERE english_word = 'bring about';
UPDATE words SET meaning = 'Đòi hỏi, yêu cầu' WHERE english_word = 'call for';
UPDATE words SET meaning = 'Tiếp tục' WHERE english_word = 'carry on';
UPDATE words SET meaning = 'Tình cờ gặp' WHERE english_word = 'come across';
UPDATE words SET meaning = 'Giải quyết, đối phó' WHERE english_word = 'deal with';
UPDATE words SET meaning = 'Cuối cùng, kết thúc' WHERE english_word = 'end up';
UPDATE words SET meaning = 'Rời khỏi, trốn thoát' WHERE english_word = 'get away';
UPDATE words SET meaning = 'Lên xe' WHERE english_word = 'get on';
UPDATE words SET meaning = 'Xuống xe' WHERE english_word = 'get off';
UPDATE words SET meaning = 'Cho đi, tặng' WHERE english_word = 'give away';
UPDATE words SET meaning = 'Tiếp tục, diễn ra' WHERE english_word = 'go on';
UPDATE words SET meaning = 'Đi chơi, tụ tập' WHERE english_word = 'hang out';
UPDATE words SET meaning = 'Kìm nén, giữ lại' WHERE english_word = 'hold back';
UPDATE words SET meaning = 'Điều tra, xem xét' WHERE english_word = 'look into';
UPDATE words SET meaning = 'Tạo nên, dẫn đến' WHERE english_word = 'make for';
UPDATE words SET meaning = 'Đi ngang qua' WHERE english_word = 'pass by';
UPDATE words SET meaning = 'Cất đi, dọn dẹp' WHERE english_word = 'put away';
UPDATE words SET meaning = 'Cán qua, chạy qua' WHERE english_word = 'run over';
UPDATE words SET meaning = 'Bắt đầu, khởi hành' WHERE english_word = 'set out';
UPDATE words SET meaning = 'Đứng dậy' WHERE english_word = 'stand up';
UPDATE words SET meaning = 'Tiếp thu, hiểu' WHERE english_word = 'take in';
UPDATE words SET meaning = 'Vứt bỏ' WHERE english_word = 'throw away';
UPDATE words SET meaning = 'Quay lại' WHERE english_word = 'turn around';
UPDATE words SET meaning = 'Chia tay, tan vỡ' WHERE english_word = 'break up';
UPDATE words SET meaning = 'Mang lại, gợi lại' WHERE english_word = 'bring back';
UPDATE words SET meaning = 'Hủy bỏ' WHERE english_word = 'call off';
UPDATE words SET meaning = 'Quay lại, trở về' WHERE english_word = 'come back';
UPDATE words SET meaning = 'Giảm bớt' WHERE english_word = 'cut down';
UPDATE words SET meaning = 'Giao, đưa đến' WHERE english_word = 'drop off';
UPDATE words SET meaning = 'Sụp đổ, tan vỡ' WHERE english_word = 'fall apart';
UPDATE words SET meaning = 'Sống qua, xoay xở' WHERE english_word = 'get by';
UPDATE words SET meaning = 'Kêu lên, nổ' WHERE english_word = 'go off';
UPDATE words SET meaning = 'Phát ra' WHERE english_word = 'hand out';
UPDATE words SET meaning = 'Tiếp tục' WHERE english_word = 'keep on';
UPDATE words SET meaning = 'Cho vào' WHERE english_word = 'let in';
UPDATE words SET meaning = 'Mong chờ' WHERE english_word = 'look forward to';
UPDATE words SET meaning = 'Bù đắp' WHERE english_word = 'make up for';
UPDATE words SET meaning = 'Chuyển tiếp, truyền lại' WHERE english_word = 'pass on';
UPDATE words SET meaning = 'Thành công, thực hiện' WHERE english_word = 'pull off';
UPDATE words SET meaning = 'Chịu đựng' WHERE english_word = 'put up with';
UPDATE words SET meaning = 'Tình cờ gặp' WHERE english_word = 'run across';
UPDATE words SET meaning = 'Tiễn đưa' WHERE english_word = 'see off';
UPDATE words SET meaning = 'Khoe khoang' WHERE english_word = 'show off';
UPDATE words SET meaning = 'Ngồi xuống' WHERE english_word = 'sit down';
UPDATE words SET meaning = 'Giống ai đó' WHERE english_word = 'take after';
UPDATE words SET meaning = 'Suy nghĩ về' WHERE english_word = 'think about';
UPDATE words SET meaning = 'Đợi, chờ đợi' WHERE english_word = 'wait for';
UPDATE words SET meaning = 'Đột nhập' WHERE english_word = 'break in';
UPDATE words SET meaning = 'Đưa lên sớm hơn' WHERE english_word = 'bring forward';
UPDATE words SET meaning = 'Gọi điện' WHERE english_word = 'call up';
UPDATE words SET meaning = 'Vào trong' WHERE english_word = 'come in';
UPDATE words SET meaning = 'Cắt bỏ' WHERE english_word = 'cut out';
UPDATE words SET meaning = 'Bãi bỏ' WHERE english_word = 'do away with';
UPDATE words SET meaning = 'Yêu, say mê' WHERE english_word = 'fall for';
UPDATE words SET meaning = 'Đi lại, di chuyển' WHERE english_word = 'get around';
UPDATE words SET meaning = 'Đồng ý với' WHERE english_word = 'go along with';
UPDATE words SET meaning = 'Giao nộp' WHERE english_word = 'hand over';
UPDATE words SET meaning = 'Tránh xa' WHERE english_word = 'keep away';
UPDATE words SET meaning = 'Tiết lộ' WHERE english_word = 'let out';
UPDATE words SET meaning = 'Coi thường' WHERE english_word = 'look down on';
UPDATE words SET meaning = 'Đưa ra, đề xuất' WHERE english_word = 'put forward';
UPDATE words SET meaning = 'Hết, cạn kiệt' WHERE english_word = 'run out';
UPDATE words SET meaning = 'Để dành, dành riêng' WHERE english_word = 'set aside';
UPDATE words SET meaning = 'Ủng hộ, đứng bên cạnh' WHERE english_word = 'stand by';
UPDATE words SET meaning = 'Đảm nhận, chấp nhận' WHERE english_word = 'take on';
UPDATE words SET meaning = 'Vứt bỏ' WHERE english_word = 'throw out';
UPDATE words SET meaning = 'Nộp, giao nộp' WHERE english_word = 'turn in';
UPDATE words SET meaning = 'Cẩn thận, coi chừng' WHERE english_word = 'watch out';
UPDATE words SET meaning = 'Bùng phát, nổ ra' WHERE english_word = 'break out';
UPDATE words SET meaning = 'Mang theo' WHERE english_word = 'bring round';
UPDATE words SET meaning = 'Trở nên phổ biến' WHERE english_word = 'catch on';
UPDATE words SET meaning = 'Đi cùng' WHERE english_word = 'come along';
UPDATE words SET meaning = 'Cắt giảm' WHERE english_word = 'cut back';
UPDATE words SET meaning = 'Cài, buộc' WHERE english_word = 'do up';
UPDATE words SET meaning = 'Dựa vào, quay lại' WHERE english_word = 'fall back on';
UPDATE words SET meaning = 'Tiến bộ, thành công' WHERE english_word = 'get ahead';
UPDATE words SET meaning = 'Quay lại, trở về' WHERE english_word = 'go back';
UPDATE words SET meaning = 'Đợi, giữ máy' WHERE english_word = 'hang on';
UPDATE words SET meaning = 'Giữ lấy, nắm lấy' WHERE english_word = 'hold on to';
UPDATE words SET meaning = 'Coi chừng, cẩn thận' WHERE english_word = 'look out';
UPDATE words SET meaning = 'Cuỗm đi, trốn với' WHERE english_word = 'make off with';
UPDATE words SET meaning = 'Đặt xuống, viết xuống' WHERE english_word = 'put down';
UPDATE words SET meaning = 'Nhìn thấu, xem xuyên qua' WHERE english_word = 'see through';
UPDATE words SET meaning = 'Dẫn tham quan' WHERE english_word = 'show around';
UPDATE words SET meaning = 'Ngồi thẳng' WHERE english_word = 'sit up';
UPDATE words SET meaning = 'Tháo rời' WHERE english_word = 'take apart';
UPDATE words SET meaning = 'Nghĩ ra' WHERE english_word = 'think up';
UPDATE words SET meaning = 'Hóa ra, kết quả là' WHERE english_word = 'turn out';
UPDATE words SET meaning = 'Phục vụ' WHERE english_word = 'wait on';
UPDATE words SET meaning = 'Mòn, cũ' WHERE english_word = 'wear out';
UPDATE words SET meaning = 'Vượt qua, đột phá' WHERE english_word = 'break through';
UPDATE words SET meaning = 'Bắt kịp với' WHERE english_word = 'catch up with';
UPDATE words SET meaning = 'Giảm xuống' WHERE english_word = 'come down';
UPDATE words SET meaning = 'Cắt đứt' WHERE english_word = 'cut off';
UPDATE words SET meaning = 'Làm mà không cần' WHERE english_word = 'do without';
UPDATE words SET meaning = 'Thất bại, không thành công' WHERE english_word = 'fall through';
UPDATE words SET meaning = 'Ám chỉ, muốn nói' WHERE english_word = 'get at';
UPDATE words SET meaning = 'Thực hiện, hoàn thành' WHERE english_word = 'go through with';
UPDATE words SET meaning = 'Tuân thủ, giữ' WHERE english_word = 'keep to';
UPDATE words SET meaning = 'Giảm bớt, ngừng' WHERE english_word = 'let up';
UPDATE words SET meaning = 'Ngưỡng mộ, tôn trọng' WHERE english_word = 'look up to';
UPDATE words SET meaning = 'Bỏ qua, bỏ sót' WHERE english_word = 'pass over';
UPDATE words SET meaning = 'Chuyển máy, kết nối' WHERE english_word = 'put through';
UPDATE words SET meaning = 'Xử lý, chăm sóc' WHERE english_word = 'see to';
UPDATE words SET meaning = 'Đóng cửa, tắt máy' WHERE english_word = 'shut down';
UPDATE words SET meaning = 'Đại diện cho, có nghĩa là' WHERE english_word = 'stand for';
UPDATE words SET meaning = 'Rút lại, lấy lại' WHERE english_word = 'take back';
UPDATE words SET meaning = 'Suy nghĩ kỹ' WHERE english_word = 'think through';
UPDATE words SET meaning = 'Biến thành' WHERE english_word = 'turn into';
UPDATE words SET meaning = 'Đợi, chờ' WHERE english_word = 'wait up';
UPDATE words SET meaning = 'Kết thúc, cuối cùng' WHERE english_word = 'wind up';
UPDATE words SET meaning = 'Vượt ngục, thoát khỏi' WHERE english_word = 'break out of';
UPDATE words SET meaning = 'Hiểu ra, nắm được' WHERE english_word = 'catch on to';
UPDATE words SET meaning = 'Gặp phải, đối mặt' WHERE english_word = 'come up against';
UPDATE words SET meaning = 'Chen hàng, cắt ngang' WHERE english_word = 'cut in';
UPDATE words SET meaning = 'Làm lại' WHERE english_word = 'do over';
UPDATE words SET meaning = 'Tụt lại phía sau, chậm trễ' WHERE english_word = 'fall behind';
UPDATE words SET meaning = 'Thoát tội, trốn tránh' WHERE english_word = 'get away with';
UPDATE words SET meaning = 'Nuốt lời, không giữ lời hứa' WHERE english_word = 'go back on';
UPDATE words SET meaning = 'Cúp máy' WHERE english_word = 'hang up';
UPDATE words SET meaning = 'Đưa ra, giữ lấy' WHERE english_word = 'hold out';
UPDATE words SET meaning = 'Bù đắp, đền bù' WHERE english_word = 'make up to';
UPDATE words SET meaning = 'Bỏ lỡ, từ chối' WHERE english_word = 'pass up';
UPDATE words SET meaning = 'Cho ở nhờ, chịu đựng' WHERE english_word = 'put up';
UPDATE words SET meaning = 'Kiệt sức, mệt mỏi' WHERE english_word = 'run down';
UPDATE words SET meaning = 'Lo việc, xử lý' WHERE english_word = 'see about';
UPDATE words SET meaning = 'Im lặng' WHERE english_word = 'shut up';
UPDATE words SET meaning = 'Nổi bật, đáng chú ý' WHERE english_word = 'stand out';
UPDATE words SET meaning = 'Nghĩ về, suy nghĩ' WHERE english_word = 'think of';
UPDATE words SET meaning = 'Thích, hứng thú với' WHERE english_word = 'turn on to';
UPDATE words SET meaning = 'Trông nom, canh giữ' WHERE english_word = 'watch over';

